services:
  agent-template:
    build: .
    container_name: agent-template
    environment:
      - OPENAI_API_KEY=""
      - GITHUB_PERSONAL_ACCESS_TOKEN=""
    stdin_open: true
    ports:
      - "5000"
    tty: true
    networks:
      - agents-net

networks:
  agents-net:
    external: true